* Ideas
** AI-powered learning companion
    - PROBLEM: Lack of utilization of AI in education (and quality of education decreasing)
    - SOLUTION:
      + empower students to learn at home
      + An AI-enabled software that uses smartphone cameras to collect data and interactively teach students
      + Will use open-ai API (or something similar) with prompt optimization features (to ensure accuracy)
** Automatic drone surveyer
    - PROBLEM: Rising food demand
    - SOLUTION:
      + Enable farmers to develop more sustainable tactics while maintaining profitability
      + Drone Aerial Mapping that uses sensors to analyze the soil, monitor crop health, etc.
      + the drone will be coupled with a computer software that will use data to analyze trends in a specific area to help with land use planning, harvest planning, etc.
** public figures profiling system
    - PROBLEM: corruption and incompetency in the government and other public offices
    - SOLUTION:
      + increase the awareness of the public and transparency
      + will use a system that will "rate" politicians based on their track records and recent deeds, will use deep learning anf other technologies to improve accuracy, up-to-date information, and interactiveness
** metropolitan companion app
    - PROBLEM: sophisticated metropolitan lifestyle
    - SOLUTION:
      + creating an integrated system that will help metropolitans to keep track of trivial stuff such as TODOs, work schedules, sleep schedules, optimal traffic routes, etc.
      + will use deep learning to learn about the users' habits, preferences, and propose routine optimization.
